### ISSUE TITLE
how to run the project

### ISSUE THREAD

**Issue by TtTRz** [FrederickGeek8/Sprint#1]
ummm i had some  troubles when i run the project.
It's loading all the time.
how to start it？？
![ele](https://user-images.githubusercontent.com/32873545/65418815-d6cb7d00-de2f-11e9-90e2-0fd2299c389f.jpg)

**Comment by FrederickGeek8** [comment]
I can check it out in detail later, but I just noticed one omission from the guide. Have you run `bower install` before launching?

**Comment by TtTRz** [comment]
ohhhhh, i didn't install it before.i'll try it now. thx!!!

**Comment by TtTRz** [comment]
It can run successfully, thank u!
